# @format

# Android API CI/CD pipelines
name: Deploy Backend CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Install the gcloud CLI
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true

      - name: Set up Prisma
        run: |
          npx prisma generate

      - name: Build and Push Docker Image
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          docker build -t us-central1-docker.pkg.dev/capstone-deploy-408008/backend-api/nginx:latest --build-arg PORT=4000 .
          docker push us-central1-docker.pkg.dev/capstone-deploy-408008/backend-api/nginx:latest

      - name: Debug
        run: ls -R
# --------------------------------------------------------------------
